[package]
name = "dotfile_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
dirs = "4"
fs_extra = "1.2.0"
maplit = "1.0.2"
